name: Lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup the Python Environment
        uses: Qwerty-133/python-setup@v1
        with:
          python-version: 3.11

      - name: Lint
        run: poetry run task lint
